sudo: required
services:
  - docker

before_install:
  - docker build -t abhishekajmera/react-1 -f Dockerfile.dev .

scripts:
  - docker run -e CI=true abhishekajmera/react-1 npm run test -- --coverage
  